# Generated by Django 4.2.3 on 2023-08-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_alquileres_id_alter_venta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='tipoPropiedad',
            new_name='tipo',
        ),
    ]
