# Generated by Django 4.2.3 on 2023-08-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_tipopropiedad_alquileres_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquileres',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
