# Generated by Django 4.2.3 on 2023-08-17 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_alquileres_id_alter_venta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='financiamiento',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
