# Generated by Django 4.2.3 on 2023-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_venta_financiamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='financiamiento',
            field=models.CharField(choices=[('Apto Financiacion', 'Apto Financiacion'), ('Efectivo', 'Efectivo')], max_length=20),
        ),
    ]
