# Generated by Django 4.2.3 on 2023-08-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_venta_financiamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='financiamiento',
        ),
    ]
