# Generated by Django 4.2.3 on 2023-08-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_inversiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileres',
            name='imagen',
            field=models.ImageField(default='imagen_no_disponible.jpg', upload_to='alquileres_images/'),
            preserve_default=False,
        ),
    ]
