# Generated by Django 4.2.3 on 2023-09-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alquileres_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquileres',
            options={'verbose_name': 'Alquiler', 'verbose_name_plural': 'Alquileres'},
        ),
        migrations.RemoveField(
            model_name='alquileres',
            name='imagen',
        ),
    ]
