# Generated by Django 4.2.3 on 2023-09-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_alquileres_options_remove_alquileres_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesores',
            options={'verbose_name': 'Asesor', 'verbose_name_plural': 'Asesores'},
        ),
    ]
