# Generated by Django 4.2.3 on 2023-09-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_alter_asesores_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inversiones',
            options={'verbose_name': 'Inversion', 'verbose_name_plural': 'Inversiones'},
        ),
    ]
